site_name: "R from a learners perspective - Data visualization"
nav:
- I. Getting started: index.md
- II. Basic usage of ggplot2 : part2.md
- III. One level up: part3.md
markdown_extensions:
- admonition
theme: readthedocs
highlights: true
use_directory_urls: true