site_name: "R from a learners perspective - The Küsel Lab (c) 2018"
nav:
- From Excel to R: index.md
- Data manipulation: part2.md
- Data visualization and exploration : part3.md
- Basic statistics: part4.md
- Multivariate analysis: part5.md
markdown_extensions:
- admonition
theme: readthedocs
highlights: true
use_directory_urls: true