site_name: "R from a learners perspective - Data visualization"
nav:
- Data manipulation: index.md
- Data visualization and exploration : part2.md
- Basic statistics: part3.md
markdown_extensions:
- admonition
theme: readthedocs
highlights: true
use_directory_urls: true